import { Montserrat } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";

const montserrat = Montserrat({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata = {
  title: "Exponential Everyday | v1",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${montserrat.variable}  text-slate-800 bg-stone-50 overflow-x-hidden`}
        >
          {children}
          <Toaster richColors />
        </body>

      </html>
    </ClerkProvider>
  );
}
